### PR TITLE
One click installer setup for MacOS

### LINKED ISSUE #948: MacOS one click installers
Add  MacOS one click click installer similar to https://github.com/h2oai/h2ogpt/issues/645

### PR DESCRIPTION
**Pull request by Mathanraj-Sharma**
Adding setups required for building one-click installers for MacOS. 

Fix #948

### CODE REVIEW

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I was able to build it successfully and run it on my Mac M1 (CPU). I will share the artifact (uploaded to our s3) with you on Slack so you can test it (if you have Mac M1). Will also ask folks from the SL team with Mac M1 to try it, and tackle the issues as they arise. 

I work on the Mac M1 (MPS) installer on a separate PR.

**Review by pseudotensor — APPROVED** [review]
cool thanks!

**Comment by Mathanraj-Sharma** [comment]
@gumbolastima Normally it should open with the terminal by default, 

After downloading, double-click on the app, "Get Info" -> "Open With" -> set to terminal

And may I know which Mac device you are using?

**Comment by Mathanraj-Sharma** [comment]
@gumbolastima it would take a few minutes to unbundle and run the app. Give it some time when the terminal opens

If it doesn't work, could you please attach the screenshot of the terminal?

**Comment by Mathanraj-Sharma** [comment]
yes, it is unsigned, I will update it on the docs. 

If you stumble into any other issue please report, it is still experimental, so your feedbacks is highly appreciated

**Pull request merged**
