### PR TITLE
made changes singtel requested

### PR DESCRIPTION
**Pull request by overaneout**

### CODE REVIEW

**Comment by overaneout** [comment]
@tomkraljevic

**Comment by pseudotensor** [comment]
@achraf-mer can you review?  Thanks!

**Review by tomkraljevic — APPROVED** [review]
looks ok to me.

**Review by EshamAaqib — APPROVED** [review]
LGTM

**Review by achraf-mer — APPROVED** [review]

**Review by ChathurindaRanasinghe — APPROVED** [review]

**Comment by pseudotensor** [comment]
There are conflicts, please help @ChathurindaRanasinghe if you can with that

**Comment by overaneout** [comment]
Fixed the merge conflict.

**Pull request merged**
