### PR TITLE
Fine tune llama2

### PR DESCRIPTION
**Pull request by arnocandel**
#573 

- [x] create new oasst1 based dataset with personalization, using `llama2` prompting https://huggingface.co/datasets/h2oai/openassistant_oasst1_h2ogpt_llama2_chat
- [ ] understand why can't put `<s>` and `</s>` into the dataset (leads to models that immediately stop generation)
- [x] understand `data_collator` argument for Trainer - not a problem, re-enabled
- [x] create oasst1+personalized fine-tune for 7b
- [ ] figure out why 7b fine-tune is busted
- [x] create oasst1+personalized fine-tune for 13b
- [x] create oasst1+personalized fine-tune for 70b
- [x] add orca_hashes prompt type https://huggingface.co/TheBloke/StableBeluga-13B-GPTQ https://discord.com/channels/1097462770674438174/1100717863221870643/1135324085434466304
- [ ] understand how to fine-tune 4K or larger contexts on 80GB GPUs

### CODE REVIEW

**Comment by arnocandel** [comment]
`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 finetune.py --data_path=h2oai/openassistant_oasst1_h2ogpt_llama2_chat --base_model=meta-llama/Llama-2-7b-chat-hf --drop_truncations=True --cutoff_len=1024 --micro_batch_size=1 --batch_size=16 --num_epochs=1 --run_id=4 --use_auth_token=True --add_eos_token=True &> log.4.txt`

**Comment by arnocandel** [comment]
`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 finetune.py --data_path=h2oai/openassistant_oasst1_h2ogpt_llama2_chat --base_model=meta-llama/Llama-2-7b-chat-hf --drop_truncations=True --cutoff_len=1024 --micro_batch_size=1 --batch_size=16 --num_epochs=1 --learning_rate=1e-5 --run_id=4 --use_auth_token=True --add_eos_token=True &> log.4.txt`

`  2%|▏         | 41/2630 [00:46<50:10,  1.16s/it]` on 2x A6000Ada 48GB

**Comment by arnocandel** [comment]
`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 finetune.py --data_path=h2oai/openassistant_oasst1_h2ogpt_llama2_chat --base_model=meta-llama/Llama-2-13b-chat-hf --drop_truncations=True --cutoff_len=1024 --micro_batch_size=1 --batch_size=16 --num_epochs=1 --learning_rate=1e-5 --run_id=5 --use_auth_token=True --add_eos_token=True &> log.5.txt`

` 18%|█▊        | 462/2630 [16:03<1:15:12,  2.08s/it]`

**Comment by arnocandel** [comment]
### 70B on 2x A100 80GB
`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 finetune.py --data_path=h2oai/openassistant_oasst1_h2ogpt_llama2_chat --base_model=meta-llama/Llama-2-70b-chat-hf --drop_truncations=True --cutoff_len=512 --micro_batch_size=1 --batch_size=2 --num_epochs=1 --learning_rate=1e-5 --run_id=6 --use_auth_token=True --add_eos_token=True --train_4bit=True &> log.6.txt`

### 13B on 2x A6000Ada 48GB
`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 finetune.py --data_path=h2oai/openassistant_oasst1_h2ogpt_llama2_chat --base_model=meta-llama/Llama-2-13b-chat-hf --drop_truncations=True --cutoff_len=1024 --micro_batch_size=1 --batch_size=16 --num_epochs=1 --learning_rate=1e-5 --run_id=7 --use_auth_token=True --add_eos_token=True &> log.7.txt`

**Comment by arnocandel** [comment]
Screenshot from 2023-07-30 12-30-49

**Review by pseudotensor — APPROVED** [review]

**Pull request merged**
