### PR TITLE
Improve docker layer caching to reduce overall image size

### PR DESCRIPTION
**Pull request by achraf-mer**
new image compared to official runtime to date:
```
harbor.h2o.ai/h2ogpt/test-image                           12e2874700679bab7bda6d5ab61a1795   1af054b005e8   40 minutes ago      20.5GB
gcr.io/vorvan/h2oai/h2ogpt-runtime                        0.1.0                              4c7dac53226f   5 days ago          49.8GB

```

### CODE REVIEW

**Review by pseudotensor — COMMENTED** [review]
I can build and run some tests.

**Comment by achraf-mer** [comment]
image

image

**Comment by achraf-mer** [comment]
vllm:

image

image

**Review by pseudotensor — APPROVED** [review]
thanks!

**Pull request merged**
