### PR TITLE
Fixes #446 Control chat history being added to context for langchain or not

### LINKED ISSUE #446: Can h2ogpt chatbox retain the context of previous questions?

### PR DESCRIPTION
**Pull request by pseudotensor**
Fixes #446 Control chat history being added to context for langchain or not

Previously LLM/ChatLLM controlled, but only for non-langchain case, and if chose collection never added chat history.

Still OpenAIChat mode doesn't support
CLI mode doesn't support -- CLI mode never supported chat history, but not hard to add.

image

image

image

### CODE REVIEW

**Comment by pseudotensor** [comment]
```
=========================== short test summary info ============================
FAILED tests/test_manual_test.py::test_chat_context - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_upload_one_file - NotImplementedError:...
FAILED tests/test_manual_test.py::test_upload_multiple_file - NotImplementedE...
FAILED tests/test_manual_test.py::test_upload_url - NotImplementedError: MANU...
FAILED tests/test_manual_test.py::test_upload_arxiv - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_upload_pasted_text - NotImplementedErr...
FAILED tests/test_manual_test.py::test_no_db_dirs - NotImplementedError: MANU...
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED tests/test_manual_test.py::test_upload_to_UserData_and_MyData - NotImp...
FAILED tests/test_manual_test.py::test_chat_control - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_subset_only - NotImplementedError: MAN...
FAILED tests/test_manual_test.py::test_add_new_doc - NotImplementedError: MAN...
FAILED tests/test_manual_test.py::test_model_lock - NotImplementedError: MANU...
= 13 failed, 219 passed, 240 skipped, 1 xpassed, 23 warnings in 12338.46s (3:25:38) =
```

**Comment by JettScythe** [comment]
Does the CLI have the same functionality as the API? 
How might I be able to pass chat_history into the gradio client?

**Comment by pseudotensor** [comment]
@this has Chat Completion API that I think handles this.

**Comment by JettScythe** [comment]
I'm not sure I understand. 
I see I can get the chat history from [the h2oGPT client](https://github.com/h2oai/h2ogpt/blob/main/client/h2ogpt_client/_core.py#L285), but I would like to be able to just pass in chat history to `run_client_chat` from [this file](https://github.com/h2oai/h2ogpt/blob/main/src/client_test.py#L266) this way I can support a multi-tenancy structure through a different backend. 
Is that possible? Is that what fields like iinput and context are for in `get_args()`?
Ideally this would be using the Gradio client

**Comment by pseudotensor** [comment]
Yes, you can maintain chat history yourself like in the gradio client case.

**Pull request merged**
