### PR TITLE
consolidate install script in one place, speed up build, + fix caching for TGI and vLLM

### PR DESCRIPTION
**Pull request by achraf-mer**
- [x] consolidate build scripts in one file.
- [x] prebuild duckdb to speedup overall docker build process.
- [x] fix caching when using TGI and vllm.
- [x] minor edits to helm chart to fix caching.
- [x] drop the Dockerfile-base and only keep one Dockerfile for convenience.

### CODE REVIEW

**Comment by achraf-mer** [comment]
hitting this annoying issue with github: 
```
[nltk_data]    | Error downloading 'universal_treebanks_v20' from
[nltk_data]    |     <https://raw.githubusercontent.com/nltk/nltk_data
[nltk_data]    |     /gh-pages/packages/corpora/universal_treebanks_v2
[nltk_data]    |     0.zip>:   HTTP Error 503: between bytes timeout
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/h2ogpt_conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/h2ogpt_conda/lib/python3.10/site-packages/nltk/downloader.py", line 2544, in <module>
    rv = downloader.download(
  File "/h2ogpt_conda/lib/python3.10/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
EOFError: EOF when reading a line
```

**Review by pseudotensor — APPROVED** [review]
Thanks!  We can merge, but I'll also test the caching thing.  I know it all worked after I made the vLLM fixes and add tests, but things probably diverged.  Hopefully now ok, but not confident till I try too.

**Comment by achraf-mer** [comment]
More cleanup to save about 3.4 GB:
image

**Comment by pseudotensor** [comment]
Thanks.  We getting rid of pkgs folder?

**Comment by achraf-mer** [comment]
> Thanks. We getting rid of pkgs folder?

which folder, the one for the conda env? my screen cap above only showed the changes from one docker layer, not everything in the image.

**Comment by achraf-mer** [comment]
image

**Comment by achraf-mer** [comment]
```
$ curl http://localhost:5000/v1/completions     -H "Content-Type: application/json"     -d '{
    "model": "h2oai/h2ogpt-4096-llama2-7b-chat",
    "prompt": "San Francisco is a",
    "max_tokens": 7,
    "temperature": 0
    }' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   455  100   321  100   134   2743   1145 --:--:-- --:--:-- --:--:--  3888
{
  "id": "cmpl-2d4878cabd7346a39a997a5455c3bbd1",
  "object": "text_completion",
  "created": 1694123472,
  "model": "h2oai/h2ogpt-4096-llama2-7b-chat",
  "choices": [
    {
      "index": 0,
      "text": "city in Northern California that is known",
      "logprobs": null,
      "finish_reason": "length"
    }
  ],
  "usage": {
    "prompt_tokens": 5,
    "total_tokens": 12,
    "completion_tokens": 7
  }
}
```

@pseudotensor will merge now to your PR, if any new change I can just submit a new one, thanks.

**Pull request merged**
