### PR TITLE
Streaming Speech-to-Text (STT) and Streaming Text-to-Speech (TTS) with Voice Cloning and Hands-Free Chat

### PR DESCRIPTION
**Pull request by pseudotensor**
- [x] Add Whisper-based STT
- [x] Don't pass to whisper entire stream, gets longer and longer.  At some point, like at old sentence break, set in stone and only append text from stream.
- [x] Want to edit. Also avoid keeping old stream, just freeze text if edit
- [x] Also freeze text if was long gap with no text.
- [x] If not same as preload, send to some GPU if want
- [x] allow separate preload
- [x] Add microsoft-based TTS with different embeddings
- [x] Add coqui-ai based TTS with different latents https://github.com/coqui-ai/TTS
- [x] Add coqui-ai voice cloning
- [x] Add control over stopping text+speech or just speech
- [x] Improve file upload button (go back from + to Upload so can be found)
- [x] Allow API to get audio for non-streaming or streaming case
- [x] Avoid audio for extraction
- [x] Update docker
- [ ] Avoid audio for summarization except for last reduction part (generally good if can isolate that)
- [ ] Iphone not updating audio correctly
- [ ] Control audio speed
- [ ] Update windows/mac if possible
- [x] Add live assistant mode (still WIP for both textual and voice control, since full voice leads to blinking of prompt)

image

### CODE REVIEW

**Comment by MSZ-MGS** [comment]
Thanks @pseudotensor for taking a time to implement this.
I checked it and found it working in general. the following issues noted:
A. I connected to the Gradio from different device, and tested Chrome and Edge. Both of them refused to give access to the MIC because the website is not secured "httpS://". However, it worked locally using "localhost"
B. I don't have a MIC, unfortunately so I used the internal mixer as a MIC (it may introduced the issue). The recognizing worked for few seconds then it stopped (the record button is still clicked).
C. I found difficulty in deleing the written text, (I forget to be honest how to repeat the issues) I have to refresh the whole website to record again.


Thanks!

**Comment by pseudotensor** [comment]
> Thanks @pseudotensor for taking a time to implement this. I checked it and found it working in general. the following issues noted: A. I connected to the Gradio from different device, and tested Chrome and Edge. Both of them refused to give access to the MIC because the website is not secured "httpS://". However, it worked locally using "localhost"

Yes, I noticed too and had added a note in docs about it.

> B. I don't have a MIC, unfortunately so I used the internal mixer as a MIC (it may introduced the issue). The recognizing worked for few seconds then it stopped (the record button is still clicked). 

Unsure what is wrong there.


> C. I found difficulty in deleing the written text, (I forget to be honest how to repeat the issues) I have to refresh the whole website to record again.

Yes, I had added to list of things to do.  That's fixed now.  By default, if you hit stop, then you can edit etc. and that will be preserved, and record will only be for next audio -> text appended to original.

**Comment by pseudotensor** [comment]
Other options:

https://huggingface.co/microsoft/speecht5_vc
https://huggingface.co/spaces/Matthijs/speecht5-vc-demo/tree/main
https://huggingface.co/spaces/Matthijs/speecht5-tts-demo/blob/main/app.py
https://huggingface.co/microsoft/speecht5_tts/discussions/16

https://github.com/suno-ai/bark
https://huggingface.co/suno/bark
https://github.com/RajKKapadia/YouTube-Text-to-Speech-Suno-Bark

file:///home/jon/h2ogpt/speech.wav
file:///home/jon/h2ogpt/bark_out.wav

https://github.com/PaddlePaddle/PaddleSpeech
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/streaming_tts_server/README.md
https://stackoverflow.com/questions/68829130/pyinstaller-modulenotfounderror-no-module-named-paddle


https://data-dive.com/realtime-audio-stream-keyword-monitoring-and-alerting-using-openai-whisper/

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI

https://huggingface.co/spaces/balacoon/tts/tree/main

https://github.com/neonbjb/tortoise-tts
https://github.com/coqui-ai/TTS/blob/dev/notebooks/Tortoise.ipynb


https://huggingface.co/spaces/aadnk/faster-whisper-webui

https://github.com/gradio-app/gradio/issues/1775
https://stackoverflow.com/questions/74660611/how-to-use-gradio-interface-to-auto-submit-the-audio-when-recording-is-done
https://github.com/gradio-app/gradio/blob/main/demo/stream_audio/run.py

**Comment by pseudotensor** [comment]
@MSZ-MGS If you have a chance, you can review the functionality.  I'm not sure about the selection of the response to speak, as that is harder to implement.  But you can always copy-paste into the instruction and have it speak that, as work-around.

**Comment by MSZ-MGS** [comment]
Fine, since this is not merged in the MAIN.
I don't know how to git clone the changes in this pull.

**Comment by MSZ-MGS** [comment]
First of all, thank you very much for the efforts. I have seen you working last three days to implment TTS and STT.
I mentioned all details below as they may help you diagnouse the issues:


I have installed the new dependicies:
pip install transformers==4.35.0
pip install accelerate==0.24.1
pip install gradio==3.50.2

Then when I launch the H2oGPT I receive below error:
--------------------------------------
Traceback (most recent call last):
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\gen.py", line 1417, in main
    raise ImportError("Install deepspeed or set --tts_coquiai_deepspeed=False")
ImportError: Install deepspeed or set --tts_coquiai_deepspeed=False
--------------------------------------
I tired to install deepspeed, I received an error.
I tried the switch (--tts_coquiai_deepspeed=False) then it worked.

When I prompted, it responded, however, after the response completed I receive below error:
----------------------------------------
Traceback (most recent call last):
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\gradio_runner.py", line 3708, in bot
    final_audio = combine_audios(audios, audio=no_audio)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\tts_utils.py", line 56, in combine_audios
    combined_wav += AudioSegment.from_raw(s, sample_width=sample_width, frame_rate=sr, channels=channels)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\pydub\audio_segment.py", line 812, in from_raw
    return cls.from_file(file, 'raw', sample_width=kwargs['sample_width'], frame_rate=kwargs['frame_rate'],
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\pydub\audio_segment.py", line 690, in from_file
    return cls(data=file.read(), metadata=metadata)
AttributeError: 'bytes' object has no attribute 'read'
----------------------------------------

Screenshot:
image

**Comment by MSZ-MGS** [comment]
Continue:

I found my commandline was not accurate, so I changed it to the below one:

python generate.py --base_model='llama' --model_path_llama=..\AddedModels\zephyr-7B-beta\zephyr-7b-beta.Q5_K_M.gguf --prompt_type=zephyr --hf_embedding_model=hkunlp/instructor-large --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --repetition_penalty=1.1 --top_p=0.9 --max_seq_len=8192 --max_input_tokens=6000 --open_browser=True --pre_load_image_audio_models=True --asr_model=openai/whisper-large-v3 --sst_model=openai/whisper-large-v3 --tts_model=tts_models/multilingual/multi-dataset/xtts_v2 --system_prompt="You are a helpful assistant named Jennifer who can hear and speak."


It downloaded some models that I received this error:

------------------------------
Traceback (most recent call last):
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\gen.py", line 1381, in main
    from image_doctr import H2OOCRLoader
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\image_doctr.py", line 15, in <module>
    from doctr.utils.common_types import AbstractFile
ModuleNotFoundError: No module named 'doctr'
------------------------------

I did:
pip install doctr

It was installed when I try to launch H2oGPT I received this error:
------------------------------
Traceback (most recent call last):
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\gen.py", line 1381, in main
    from image_doctr import H2OOCRLoader
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\image_doctr.py", line 15, in <module>
    from doctr.utils.common_types import AbstractFile
ModuleNotFoundError: No module named 'doctr.utils'
------------------------------

I did:
pip install doctr.utils <it didn't work>

I found this on the internet
pip install python-doctr

After installation (there are few errors in the installation, but that didn't stop it).
I launched the H2oGPT and received below errors:

------------------------------
python generate.py --base_model='llama' --model_path_llama=..\AddedModels\zephyr-7B-beta\zephyr-7b-beta.Q5_K_M.gguf --prompt_type=zephyr --hf_embedding_model=hkunlp/instructor-large --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --repetition_penalty=1.1 --top_p=0.9 --max_seq_len=8192 --max_input_tokens=6000 --open_browser=True --pre_load_image_audio_models=True --asr_model=openai/whisper-large-v3 --sst_model=openai/whisper-large-v3 --tts_model=tts_models/multilingual/multi-dataset/xtts_v2 --system_prompt="You are a helpful assistant named Jennifer who can hear and speak."
Fontconfig error: Cannot load default config file: No such file: (null)
Using Model llama
load INSTRUCTOR_Transformer
max_seq_length  512
Downloading https://doctr-static.mindee.com/models?id=v0.3.1/db_resnet50-ac60cadc.pt&src=0 to G:\Users\mazen\.cache\doctr\models\db_resnet50-ac60cadc.pt
101971968it [00:16, 6070490.14it/s]
Traceback (most recent call last):
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\gen.py", line 1382, in main
    doctr_loader = H2OOCRLoader(layout_aware=True, gpu_id=doctr_gpu_id).load_model()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\h2ogpt\src\image_doctr.py", line 59, in load_model
    self._ocr_model = ocr_predictor(det_arch="db_resnet50", reco_arch="crnn_efficientnetv2_mV2",
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\doctr\models\zoo.py", line 106, in ocr_predictor
    return _predictor(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\doctr\models\zoo.py", line 42, in _predictor
    reco_predictor = recognition_predictor(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\doctr\models\recognition\zoo.py", line 73, in recognition_predictor
    return _predictor(arch, pretrained, **kwargs)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\doctr\models\recognition\zoo.py", line 32, in _predictor
    raise ValueError(f"unknown architecture '{arch}'")
ValueError: unknown architecture 'crnn_efficientnetv2_mV2'
------------------------------


it is clearly I am going no where...

**Comment by pseudotensor** [comment]
@MSZ-MGS Thanks for trying it out!

* I added a check if don't have docTR installed so it gets disabled for preloading, thanks.
* You don't have to do general preloading if only doing TTS and STT, but shouldn't matter after docTR fix.

The original error you posted is most relevant:
```
AttributeError: 'bytes' object has no attribute 'read'
```

I think you said you don't have a microphone right?  So you wouldn't be able to test that aspect.  So you would do `--enable_stt=False`.  I think you must have done that, so good.

When I run with:
```
python generate.py --verbose=True --score_model=None --base_model=TheBloke/zephyr-7B-beta-GGUF --enable_stt=False
```

I don't see the error you showed.  I'll try to see how happens.

**Pull request merged**
