### PR TITLE
Rebuild duckdb with control over threads to avoid excessive threads per db when system has large core count

### PR DESCRIPTION
**Pull request by pseudotensor**

### CODE REVIEW

**Comment by achraf-mer** [comment]
merged some changes, I dropped `TRANSFORMERS_CACHE="/.cache/"` because it should have been set to `/.cache/huggingface/hub/` but we don't need to do that, TGI already sets to `/data`.

If kept for example in vllm, then ends up with some data under the hub subdir, and some at top level, e.g. from before this PR:

image

`cache` after running h2oGPT without vllm, and `cache2` set to cache dir for vllm.

**Comment by pseudotensor** [comment]
I confirmed before changes that I can build docker image with older way.

I confirmed new duckdb in docker responds to new env:

```
jon@gpu:/data/jon/h2ogpt_docker$ docker run -ti --entrypoint=bash h2ogpt
h2ogpt@035e5887308a:~$ DUCKDB_NUM_THREADS=7 python3.10
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> 
```
separate docker exec:
```
jon@gpu:/data/jon/h2ogpt_docker$ docker exec -ti 035e5887308a bash
h2ogpt@035e5887308a:~$ ps -auxwf
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
h2ogpt        87  0.1  0.0   4248  3464 pts/1    Ss   22:12   0:00 bash
h2ogpt        94  0.0  0.0   6140  2936 pts/1    R+   22:13   0:00  \_ ps -auxwf
h2ogpt         1  0.0  0.0   4248  3420 pts/0    Ss   22:11   0:00 bash
h2ogpt        80  0.1  0.0 118624 37072 pts/0    Sl+  22:12   0:00 python3.10
h2ogpt@035e5887308a:~$ ps -o nlwp 80
NLWP
   7
h2ogpt@035e5887308a:~$ 

```

**Comment by pseudotensor** [comment]
most tests pass, merging for testing on public  portal, will share final test results once done.

**Comment by pseudotensor** [comment]
```
=========================== short test summary info ============================
FAILED tests/test_client_calls.py::test_client_chat_stream_langchain_steps[100-256]
FAILED tests/test_client_calls.py::test_client_chat_stream_langchain_steps[100-2048]
FAILED tests/test_client_calls.py::test_fastsys[True-None-instruct_vicuna] - ...
FAILED tests/test_client_calls.py::test_fastsys[True-None-one_shot] - Asserti...
FAILED tests/test_client_calls.py::test_fastsys[False-None-instruct_vicuna]
FAILED tests/test_client_calls.py::test_fastsys[False-None-one_shot] - Assert...
FAILED tests/test_inference_servers.py::test_openai_inference_server[openai_azure_chat-False]
FAILED tests/test_inference_servers.py::test_openai_inference_server[openai_azure_chat-True]
FAILED tests/test_langchain_units.py::test_qa_wiki_db_chunk_hf_dbs_llama[chroma]
FAILED tests/test_langchain_units.py::test_url_more_subunit - assert 0 > 0
FAILED tests/test_long_context.py::test_gradio_long_context_uuid_key_value_retrieval[False-0.2-5000-{'type':'dynamic', 'factor':2}-h2oai/h2ogpt-4096-llama2-13b-chat]
FAILED tests/test_long_context.py::test_gradio_long_context_uuid_key_value_retrieval[False-0.2-6000-{'type':'dynamic', 'factor':2}-h2oai/h2ogpt-4096-llama2-13b-chat]
FAILED tests/test_long_context.py::test_gradio_long_context_uuid_key_value_retrieval[True-0.2-6000-{'type':'dynamic', 'factor':2}-h2oai/h2ogpt-4096-llama2-13b-chat]
FAILED tests/test_manual_test.py::test_chat_context - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_upload_one_file - NotImplementedError:...
FAILED tests/test_manual_test.py::test_upload_multiple_file - NotImplementedE...
FAILED tests/test_manual_test.py::test_upload_url - NotImplementedError: MANU...
FAILED tests/test_manual_test.py::test_upload_arxiv - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_upload_pasted_text - NotImplementedErr...
FAILED tests/test_manual_test.py::test_no_db_dirs - NotImplementedError: MANU...
FAILED tests/test_manual_test.py::test_upload_unsupported_file - NotImplement...
FAILED tests/test_manual_test.py::test_upload_to_UserData_and_MyData - NotImp...
FAILED tests/test_manual_test.py::test_chat_control - NotImplementedError: MA...
FAILED tests/test_manual_test.py::test_subset_only - NotImplementedError: MAN...
FAILED tests/test_manual_test.py::test_add_new_doc - NotImplementedError: MAN...
FAILED tests/test_manual_test.py::test_model_lock - NotImplementedError: MANU...
FAILED tests/test_metrics.py::test_bleurt - ImportError: To be able to use ev...
FAILED tests/test_metrics.py::test_bertscore - ImportError: To be able to use...
FAILED tests/test_metrics.py::test_wiki_split - ImportError: To be able to us...
FAILED tests/test_requirements.py::test_requirements - ValueError: ['numpy==1...
= 30 failed, 1316 passed, 278 skipped, 6 xfailed, 1 xpassed, 31 warnings in 20089.51s (5:34:49) =

```

**Pull request merged**
