### PR TITLE
More weaviate tests

### PR DESCRIPTION
**Pull request by pseudotensor**
FYI @hsm207 

```
============================================================================================================ short test summary info ============================================================================================================
FAILED tests/test_langchain_units.py::test_make_add_db[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_zip_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_url_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_html_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_docx_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_md_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_eml_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_simple_eml_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_odt_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_pptx_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_simple_pptx_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_epub_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_png_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_png_add_gpu[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_png_add_gpu_preload[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_png_add_gpu_blip2[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
FAILED tests/test_langchain_units.py::test_simple_rtf_add[weaviate] - TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
================================================================================== 17 failed, 26 passed, 8 skipped, 1 xpassed, 8 warnings in 501.87s (0:08:21) ==================================================================================
```

```
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jon/h2ogpt/utils.py", line 750, in _traced_func
    return func(*args, **kwargs)
  File "/home/jon/h2ogpt/tests/test_langchain_units.py", line 528, in test_png_add_gpu_blip2
    return run_png_add(captions_model='Salesforce/blip2-flan-t5-xl', caption_gpu=True, db_type=db_type)
  File "/home/jon/h2ogpt/tests/test_langchain_units.py", line 543, in run_png_add
    db = make_db_main(persist_directory=tmp_persistent_directory, user_path=tmp_user_path,
  File "/home/jon/h2ogpt/make_db.py", line 150, in make_db_main
    db = _create_or_update_weaviate_db(sources, use_openai_embedding, add_if_exists, verbose, hf_embedding_model, collection_name)
  File "/home/jon/h2ogpt/make_db.py", line 186, in _create_or_update_weaviate_db
    db = Weaviate(embedding_function=embedding, client=client, by_text=False, index_name=index_name)
TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding_function'
```

Also see during pytest:
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23it/s]
0it [00:00, ?it/s]
Exceptions: []
embedded weaviate is already listening on port 6666
FAILED
```

Seems like weaviate is not shutting down after test completed, which is odd since should be in fork.

### CODE REVIEW

**Comment by pseudotensor** [comment]
Even pycharm showed problems, and `db` wasn't returned.  Trying tests again after changes

**Comment by pseudotensor** [comment]
```
============================================================================================================ short test summary info ============================================================================================================
FAILED tests/test_langchain_units.py::test_make_add_db[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_zip_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_url_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_html_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_docx_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_md_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_eml_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_simple_eml_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_odt_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_pptx_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_simple_pptx_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_epub_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_png_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_png_add_gpu[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_png_add_gpu_preload[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_png_add_gpu_blip2[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
FAILED tests/test_langchain_units.py::test_simple_rtf_add[weaviate] - TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
================================================================================== 17 failed, 26 passed, 8 skipped, 1 xpassed, 8 warnings in 517.44s (0:08:37) ==================================================================================
(h2ollm) jon@pseudotensor:~/h2ogpt$ 

```

**Comment by pseudotensor** [comment]
```
"""
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jon/h2ogpt/utils.py", line 750, in _traced_func
    return func(*args, **kwargs)
  File "/home/jon/h2ogpt/tests/test_langchain_units.py", line 580, in test_simple_rtf_add
    db = make_db_main(persist_directory=tmp_persistent_directory, user_path=tmp_user_path,
  File "/home/jon/h2ogpt/make_db.py", line 147, in make_db_main
    db = _create_or_update_weaviate_db(sources, use_openai_embedding, add_if_exists, verbose, hf_embedding_model,
  File "/home/jon/h2ogpt/make_db.py", line 186, in _create_or_update_weaviate_db
    db = Weaviate(embedding=embedding, client=client, by_text=False, index_name=index_name)
TypeError: Weaviate.__init__() missing 1 required positional argument: 'text_key'
"""

```

**Comment by hsm207** [comment]
@pseudotensor I'll have a look next week. Any chance you can give me permission to push commits to this PR?

**Comment by pseudotensor** [comment]
```
============================================================================================================ short test summary info ============================================================================================================
FAILED tests/test_langchain_units.py::test_zip_add[weaviate] - AssertionError: assert 3 == 1
FAILED tests/test_langchain_units.py::test_html_add[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_eml_add[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_simple_eml_add[weaviate] - assert 4 == 1
FAILED tests/test_langchain_units.py::test_pptx_add[weaviate] - AssertionError: assert 'Presentation' in 'Michelle holds a B.A. in Mathematics and Computer Science from Ursinus College. In her downtime, she enjoys spending quality time with her family and expressing her creativity by playing the bas...
FAILED tests/test_langchain_units.py::test_simple_pptx_add[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_epub_add[weaviate] - AssertionError: assert ('happy' in 'Hello World' or 'happiness' in 'Hello World')
FAILED tests/test_langchain_units.py::test_png_add[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_png_add_gpu[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_png_add_gpu_preload[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_png_add_gpu_blip2[weaviate] - AssertionError: assert 4 == 1
FAILED tests/test_langchain_units.py::test_simple_rtf_add[weaviate] - AssertionError: assert 'Microsoft' in 'Light;lue0;ed0lue255;ed0lue255;ed0lue0;ed255lue255;ed255lue0;ed255lue0;ed255lue255;tnbj\n4s18 4s18 21 Sample Rich Text Format Document'
================================================================================== 12 failed, 33 passed, 8 skipped, 1 xpassed, 8 warnings in 550.00s (0:09:09) ==================================================================================
(h2ollm) jon@pseudotensor:~/h2ogpt$ 

```

**Comment by pseudotensor** [comment]
```
======================================================================================= 47 passed, 8 skipped, 1 xpassed, 8 warnings in 677.17s (0:11:17) ========================================================================================
(h2ollm) jon@pseudotensor:~/h2ogpt$ pytest -s -v tests/test_langchain_units.py

```

**Comment by pseudotensor** [comment]
@hsm207 I fixed things probably, but please take a look.

**Comment by hsm207** [comment]
> Also see during pytest:
> 
> ```
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.23it/s]
> 0it [00:00, ?it/s]
> Exceptions: []
> embedded weaviate is already listening on port 6666
> FAILED
> ```
> 
> Seems like weaviate is not shutting down after test completed, which is odd since should be in fork.

@pseudotensor the lifetime of an embedded weaviate instance follows the process that spawned it. So, in the context of a test, if the test creates an embedded weaviate instance, then it will be destroyed when the test is over.

For example, running a test script that has these two tests:

```python
import weaviate
from weaviate.embedded import EmbeddedOptions

def test_foo():
    client = weaviate.Client(
    embedded_options=EmbeddedOptions()
    )


def test_bar():
    client = weaviate.Client(
    embedded_options=EmbeddedOptions()
    )

``` 

will result in the following output:

> ======================================================================= test session starts =======================================================================
> platform linux -- Python 3.8.13, pytest-7.2.2, pluggy-1.0.0
> rootdir: /workspaces/h2ogpt
> plugins: xdist-3.2.1, anyio-3.7.0, cov-3.0.0, pythonpath-0.7.4, hypothesis-4.50.8
> collected 2 items                                                                                                                                                 
> 
> ../tests/test_demo_weaviate_embedded.py Started /root/.cache/weaviate-embedded: process ID 19235
> {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-06-05T12:07:59Z"}
> {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-06-05T12:07:59Z"}
> {"level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2023-06-05T12:07:59Z"}
> {"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Shutting down... ","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Stopped serving weaviate at http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}
> .Started /root/.cache/weaviate-embedded: process ID 19278
> {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2023-06-05T12:07:59Z"}
> {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2023-06-05T12:07:59Z"}
> {"level":"warning","msg":"Multiple vector spaces are present, GraphQL Explore and REST API list objects endpoint module include params has been disabled as a result.","time":"2023-06-05T12:07:59Z"}
> {"action":"grpc_startup","level":"info","msg":"grpc server listening at [::]:50051","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Serving weaviate at http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Shutting down... ","time":"2023-06-05T12:07:59Z"}
> {"action":"restapi_management","level":"info","msg":"Stopped serving weaviate at http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}
> .                                                                                                                  [100%]
> 
> ======================================================================== 2 passed in 0.73s ========================================================================

Notice that this set of messages:

```
{"action":"restapi_management","level":"info","msg":"Serving weaviate at [http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}](http://127.0.0.1:6666%22%2C%22time%22:%222023-06-05t12:07:59Z%22%7D/)
{"action":"restapi_management","level":"info","msg":"Shutting down... ","time":"2023-06-05T12:07:59Z"}
{"action":"restapi_management","level":"info","msg":"Stopped serving weaviate at [http://127.0.0.1:6666","time":"2023-06-05T12:07:59Z"}](http://127.0.0.1:6666%22%2C%22time%22:%222023-06-05t12:07:59Z%22%7D/)
```
appears twice.

Therefore, if you see this message:

> embedded weaviate is already listening on port 6666

It means either:

1. You had spawned embedded weaviate in a separate process that is still running e.g. you opened a python terminal and ran the code to create embeddded weaviate and did not exit the terminal, or

2. The vector store component is part of a global variable that persist for the entire test session

**Comment by pseudotensor** [comment]
> @pseudotensor the lifetime of an embedded weaviate instance follows the process that spawned it. So, in the context of a test, if the test creates an embedded weaviate instance, then it will be destroyed when the test is over.

Understood, but these test are wrapped in a subprocess fork call, and all tests are called sequentially with pytest (no -n X), so I'd expect every new test to be fully isolated.  The only case when this wouldn't be true is if weaviate launches a process and detatches from the parent.

**Comment by hsm207** [comment]
I wrapped the tests int the `wrap_test_forked` decorator:

```python
import weaviate
from weaviate.embedded import EmbeddedOptions
from tests.utils import wrap_test_forked


@wrap_test_forked
def test_foo():
    client = weaviate.Client(
    embedded_options=EmbeddedOptions()
    )

@wrap_test_forked
def test_bar():
    client = weaviate.Client(
    embedded_options=EmbeddedOptions()
    )

```
and the output still repeats 2x. So, we can conclude from this that weaviate does not launch a process and detaches it from the parent, right?

**Comment by pseudotensor** [comment]
ok

**Comment by hsm207** [comment]
this behavior might be due to weaviate/weaviate-python-client#349. We should upgrade the client once the fix is released.

**Pull request merged**
