### PR TITLE
feat: Qdrant vector store

### LINKED ISSUE #149: add support for qdrant
https://qdrant.tech/

### PR DESCRIPTION
**Pull request by Anush008**
Adds support for Qdrant - https://qdrant.tech to be used as a supported vector database.

Resolves #149|

I've managed to run most of the unit tests. Few caused OOM issues.

### CODE REVIEW

**Comment by pseudotensor** [comment]
Cool thanks!

**Comment by Anush008** [comment]
Hi @pseudotensor. Could you take a look when possible please?

**Comment by pseudotensor** [comment]
Thanks!  Will do.

**Review by pseudotensor — APPROVED** [review]
Looks good, I'll do more extensive testing once merged in nightly.

**Comment by pseudotensor** [comment]
FYI @Anush008 

```
__________________________ test_make_add_db[qdrant-0] __________________________
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jon/h2ogpt/src/utils.py", line 1025, in _traced_func
    return func(*args, **kwargs)
  File "/home/jon/h2ogpt/tests/test_langchain_units.py", line 495, in test_make_add_db
    get_source_files(db=db)
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 8373, in get_source_files
    metadatas = get_metadatas(db, full_required=False)
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 5209, in get_metadatas
    metadatas = [point.payload["metadata"] for point in points]
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 5209, in <listcomp>
    metadatas = [point.payload["metadata"] for point in points]
AttributeError: 'list' object has no attribute 'payload'
```

Also, many of the tests that test counts of documents is off, but that's less urgent.

**Pull request merged**
